# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Env',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('comment', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'deploy_env',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='标题')),
                ('vcs_type', models.CharField(max_length=255, unique=True, verbose_name='仓库类型, git or svn')),
                ('repository_url', models.CharField(max_length=255, unique=True, verbose_name='仓库地址')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='备注')),
                ('status', models.CharField(default=0, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'deploy_project',
            },
        ),
        migrations.CreateModel(
            name='ProjectConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=255, unique=True, verbose_name='分支名')),
                ('dest_path', models.CharField(max_length=255, unique=True, verbose_name='目标路径')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('env', models.ManyToManyField(to='deploy.Env')),
                ('project', models.ManyToManyField(to='deploy.Project')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'deploy_project_config',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_host_status', models.TextField(default='', verbose_name='发布主机状态')),
                ('has_rollback', models.CharField(default='0', max_length=255, verbose_name='有无回滚')),
                ('status', models.CharField(default='0', max_length=255, verbose_name='状态')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='env', to='deploy.Env')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='deploy.Project')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'deploy_task',
            },
        ),
    ]
