# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectconfig',
            options={'verbose_name': '项目部署配置', 'verbose_name_plural': '项目部署配置'},
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('2', '禁用')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='vcs_type',
            field=models.CharField(choices=[('git', 'GIT'), ('svn', 'SVN')], default='git', max_length=255, verbose_name='仓库类型'),
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='env',
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='env',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Env'),
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='project',
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Project'),
        ),
    ]
