# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 16:14
from __future__ import unicode_literals

from django.db import migrations


def load_envs(apps, schema_editor):
    try:
        Env = apps.get_model("deploy", "Env")
        env = Env(name='生产', comment='线上环境')
        env.save()
        env = Env(name='仿真', comment='模拟生产环境')
        env.save()
        env = Env(name='测试', comment='用于QA测试')
        env.save()
    except:
        pass

def delete_envs(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_envs, delete_envs),
    ]
