# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20181111_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfig',
            name='env',
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='env',
            field=models.ManyToManyField(to='deploy.Env'),
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='project',
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='project',
            field=models.ManyToManyField(to='deploy.Project'),
        ),
    ]
