# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-06 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20190106_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dest_path',
            field=models.CharField(default='', max_length=255, verbose_name='部署路径'),
        ),
    ]
