# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_auto_20181111_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfig',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.ProjectConfig'),
        ),
    ]
