# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20181111_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectconfig',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='deploy.ProjectConfig'),
        ),
    ]
