# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0005_task_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version_message',
            field=models.CharField(default='', max_length=255, verbose_name='版本注释'),
        ),
    ]
