# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-11 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0006_task_version_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rsync_enable_delete',
            field=models.BooleanField(default=False, verbose_name='启用rsync删除选项'),
        ),
        migrations.AlterField(
            model_name='project',
            name='exclude_file',
            field=models.TextField(blank=True, default='', null=True, verbose_name='rsync排除文件'),
        ),
    ]
