# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_auto_20181111_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfig',
            name='env',
        ),
        migrations.AddField(
            model_name='projectconfig',
            name='env',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Env'),
        ),
    ]
