# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-14 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_auto_20190111_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enable_mail_notify',
            field=models.BooleanField(default=False, verbose_name='启用邮件通知'),
        ),
    ]
