# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_auto_20181111_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_config',
        ),
        migrations.AddField(
            model_name='project',
            name='branch',
            field=models.CharField(default='master', max_length=255, verbose_name='分支名'),
        ),
        migrations.AddField(
            model_name='project',
            name='env',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Env'),
        ),
    ]
