# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_auto_20181111_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfig',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='dest_path',
        ),
        migrations.RemoveField(
            model_name='projectconfig',
            name='env',
        ),
        migrations.AddField(
            model_name='project',
            name='dest_rootpath',
            field=models.CharField(default='', max_length=255, verbose_name='目标根路径'),
        ),
    ]
