# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-11 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0010_auto_20181111_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectconfig',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectConfig',
        ),
    ]
