# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20181113_2029'),
        ('deploy', '0012_auto_20181113_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEnvConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(default='master', max_length=255, verbose_name='分支名')),
                ('env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Env')),
                ('host_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.HostGroup')),
            ],
            options={
                'verbose_name': '项目环境配置',
                'verbose_name_plural': '项目环境配置',
                'db_table': 'deploy_project_env_config',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='project',
            name='env',
        ),
        migrations.AddField(
            model_name='projectenvconfig',
            name='project',
            field=models.ManyToManyField(to='deploy.Project'),
        ),
    ]
