# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0013_auto_20181113_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectenvconfig',
            name='project',
        ),
        migrations.AddField(
            model_name='projectenvconfig',
            name='project',
            field=models.IntegerField(null=True, verbose_name='项目ID'),
        ),
    ]
