# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0015_auto_20181113_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='名称'),
        ),
    ]
