# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0016_auto_20181113_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deploy_mode',
            field=models.CharField(choices=[('0', '增量'), ('1', '全量')], default='0', max_length=2, verbose_name='部署模式'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.CharField(max_length=255, verbose_name='仓库地址'),
        ),
    ]
