# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0017_auto_20181114_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvconfig',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deploy.Project'),
        ),
    ]
