# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0018_auto_20181114_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectenvconfig',
            old_name='pid',
            new_name='project',
        ),
    ]
