# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-14 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0019_auto_20181114_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectenvconfig',
            name='branch',
            field=models.CharField(default='master', max_length=255, null=True, verbose_name='分支名'),
        ),
    ]
