# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0020_auto_20181114_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='project',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='username'),
        ),
    ]
