# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0021_auto_20181121_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, '用户名和密码'), (2, '用户名和私钥')], default=1, max_length=2)),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('private_key', models.TextField(default='', verbose_name='私钥json')),
                ('passphrase', models.CharField(default='', max_length=255, verbose_name='口令-私钥')),
                ('comment', models.CharField(default='', max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '凭据',
                'verbose_name_plural': '凭据',
                'db_table': 'deploy_credentials',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='password',
        ),
        migrations.RemoveField(
            model_name='project',
            name='username',
        ),
        migrations.AddField(
            model_name='project',
            name='credentials',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='deploy.Credentials'),
        ),
    ]
