# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0022_auto_20181121_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='credentials',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
