# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0023_auto_20181126_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dest_rootpath',
        ),
        migrations.AddField(
            model_name='project',
            name='dest_path',
            field=models.CharField(default='', max_length=255, verbose_name='根路径'),
        ),
    ]
