# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0026_setting_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(default='0', max_length=255, verbose_name='发送人')),
                ('host', models.CharField(default='', max_length=255, verbose_name='发送人')),
                ('port', models.CharField(default='25', max_length=255, verbose_name='发送人')),
                ('username', models.CharField(default='', max_length=255, verbose_name='发送人账号')),
                ('password', models.CharField(default='', max_length=255, verbose_name='发送人密码')),
                ('use_tls', models.BooleanField(default=True, verbose_name='发送人密码')),
            ],
            options={
                'verbose_name': '设置 - 邮箱',
                'verbose_name_plural': '设置 - 邮箱',
                'db_table': 'deploy_setting_mail',
            },
        ),
        migrations.DeleteModel(
            name='Setting_mail',
        ),
    ]
