# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-12 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0027_auto_20181212_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingLdap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=255, verbose_name='发送人')),
                ('port', models.CharField(default='389', max_length=255, verbose_name='发送人')),
                ('uid', models.CharField(default='uid', max_length=255, verbose_name='uid')),
                ('base', models.CharField(default='uid', max_length=255, verbose_name='base')),
                ('bind_dn', models.CharField(default='', max_length=255, verbose_name='bind_dn')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
            ],
            options={
                'verbose_name': '设置 - LDAP',
                'verbose_name_plural': '设置 - LDAP',
                'db_table': 'deploy_setting_ldap',
            },
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='host',
            field=models.CharField(default='', max_length=255, verbose_name='主机'),
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='port',
            field=models.CharField(default='25', max_length=255, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='TLS'),
        ),
    ]
