# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-14 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0028_auto_20181212_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_register', models.BooleanField(default=True, verbose_name='开启注册')),
            ],
            options={
                'verbose_name': '设置 - 通用',
                'verbose_name_plural': '设置 - 通用',
                'db_table': 'deploy_setting_general',
            },
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='from_email',
            field=models.CharField(default='', help_text='例: opendeploy@ninjacn.com或Opendeploy<opendeploy@ninjacn.com>', max_length=255, verbose_name='发送人'),
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='host',
            field=models.CharField(default='', help_text='例: smtp.exmail.qq.com', max_length=255, verbose_name='SMTP主机'),
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='发送人密码'),
        ),
        migrations.AlterField(
            model_name='settingmail',
            name='use_tls',
            field=models.BooleanField(default=False, verbose_name='TLS'),
        ),
    ]
