# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-18 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0031_auto_20181216_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='dest_path',
            field=models.CharField(default='', max_length=255, verbose_name='项目路径'),
        ),
    ]
