# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0032_auto_20181218_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenvconfig',
            name='after_hook',
            field=models.TextField(default='', verbose_name='发布后钩子'),
        ),
        migrations.AddField(
            model_name='projectenvconfig',
            name='before_hook',
            field=models.TextField(default='', verbose_name='发布前钩子'),
        ),
    ]
