# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-22 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0033_auto_20181222_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('0', '待发布'), ('1', '正在发布'), ('2', '发布成功'), ('3', '发布失败')], default='0', max_length=16, verbose_name='状态'),
        ),
    ]
