# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-23 05:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deploy', '0034_auto_20181223_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
