# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0035_task_creater'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectenvconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='projectenvconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
