# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0036_auto_20181227_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dingding_robot_webhook',
            field=models.CharField(default='', max_length=255, verbose_name='钉钉机器人webhook'),
        ),
    ]
