# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-28 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0037_project_dingding_robot_webhook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': '认证凭证', 'verbose_name_plural': '认证凭证'},
        ),
        migrations.AlterField(
            model_name='project',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='project',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='deploy.Credentials'),
        ),
        migrations.AlterField(
            model_name='project',
            name='dingding_robot_webhook',
            field=models.URLField(blank=True, default='', max_length=255, null=True, verbose_name='钉钉机器人webhook'),
        ),
    ]
