# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0038_auto_20181228_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='1', max_length=2, verbose_name='状态'),
        ),
    ]
