# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-01 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0039_auto_20181229_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='exclude_file',
            field=models.TextField(default='', verbose_name='排除文件'),
        ),
    ]
