version: '3'
services:
  web:
    image: ninjacn/opendeploy
    command: 'python /app/manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./src:/app
      - ./logs/app:/app/storage/logs
      - ./logs/release_log:/app/storage/release_log
      - ./data/exclude_file:/app/storage/exclude_file
      - ./data/files:/app/storage/files
      - ./data/hooks:/app/storage/hooks
      - ./data/privary_key:/app/storage/privary_key
    ports:
      - 10080:8000
    env_file: 
      - .env
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  worker:
    image: ninjacn/opendeploy
    command: 'celery -A opendeploy worker --concurrency=5 -l info'
    volumes:
      - ./src:/app
      - ./logs/app:/app/storage/logs
      - ./logs/release_log:/app/storage/release_log
      - ./data/exclude_file:/app/storage/exclude_file
      - ./data/files:/app/storage/files
      - ./data/hooks:/app/storage/hooks
      - ./data/privary_key:/app/storage/privary_key
      - ./data/workspace:/root/.opendeploy/workspace
    env_file: 
      - .env
    links:
      - db
      - redis
      - rabbit
    depends_on:
      - db
      - redis
      - rabbit
  beat:
    image: ninjacn/opendeploy
    command: 'celery -A opendeploy beat -l info'
    volumes:
      - ./src:/app
      - ./logs/app:/app/storage/logs
      - ./logs/release_log:/app/storage/release_log
      - ./data/exclude_file:/app/storage/exclude_file
      - ./data/files:/app/storage/files
      - ./data/hooks:/app/storage/hooks
      - ./data/privary_key:/app/storage/privary_key
    env_file: 
      - .env
    links:
      - db
      - rabbit
    depends_on:
      - db
      - rabbit
  db:
    image: mysql:5.6
    restart: always
    command: ['mysqld']
    volumes:
      - ./conf/mysql/mysqld.cnf:/etc/mysql/conf.d/docker.cnf
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: opendeploy
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Wh4LsrGxpg59XUuH
      MYSQL_PASSWORD: Wh4LsrGxpg59XUuH
    ports:
      - 13306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 10s
        retries: 10
  rabbit:
      image: rabbitmq:latest
      ports:
          - 10082:15672
  redis:
      image: redis:5
      ports:
          - 10083:6379
  adminer:
    image: adminer
    restart: always
    ports:
      - 10081:8080
