version: '3'
services:
  nginx:
    image: nginx:latest
  web:
    image: ninjacn/opendeploy:latest
    command: 'python /app/manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./src:/app
      - ./logs/app:/app/storage/logs
      - ./logs/release_log:/app/storage/release_log
      - ./data/exclude_file:/app/storage/exclude_file
      - ./data/files:/app/storage/files
      - ./data/hooks:/app/storage/hooks
      - ./data/privary_key:/app/storage/privary_key
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
  worker:
    image: ninjacn/opendeploy:latest
    command: 'celery -A opendeploy worker --concurrency=5 -l info'
    volumes:
      - ./src:/app
      - ./logs/app:/app/storage/logs
      - ./logs/release_log:/app/storage/release_log
      - ./data/exclude_file:/app/storage/exclude_file
      - ./data/files:/app/storage/files
      - ./data/hooks:/app/storage/hooks
      - ./data/privary_key:/app/storage/privary_key
      - ./data/workspace:/root/.opendeploy/workspace
    links:
      - db
      - redis
      - rabbit
    depends_on:
      - db
      - redis
      - rabbit
  beat:
    image: ninjacn/opendeploy:latest
    command: 'celery -A opendeploy beat -l info'
    volumes:
      - ./src:/app
      - ./logs/app:/app/storage/logs
      - ./logs/release_log:/app/storage/release_log
      - ./data/exclude_file:/app/storage/exclude_file
      - ./data/files:/app/storage/files
      - ./data/hooks:/app/storage/hooks
      - ./data/privary_key:/app/storage/privary_key
    links:
      - db
      - rabbit
    depends_on:
      - db
      - rabbit
  db:
    image: ninjacn/opendeploy_mysql:latest
    restart: always
    command: ['mysqld']
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 13306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 10s
        retries: 10
  rabbit:
      image: rabbitmq:latest
      ports:
          - 10082:15672
  redis:
      image: redis:5
      ports:
          - 10083:6379
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 10081:8080
