version: '3'
services:
  nginx:
    image: ninjacn/opendeploy_nginx:latest
  web:
    image: ninjacn/opendeploy:latest
    command: 'python /app/manage.py runserver 0.0.0.0:8000'
    env_file: 
      - .env.local
  worker:
    image: ninjacn/opendeploy:latest
    command: 'celery -A opendeploy worker --concurrency=2 -l info'
    env_file: 
      - .env.local
  beat:
    image: ninjacn/opendeploy:latest
    env_file: 
      - .env.local
  docs:
    image: ninjacn/opendeploy:latest
    ports:
      - 10084:8000
  db:
    environment:
      MYSQL_DATABASE: opendeploy
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Wh4LsrGxpg59XUuH
      MYSQL_PASSWORD: Wh4LsrGxpg59XUuH
  rabbit:
      image: rabbitmq:latest
  redis:
      image: redis:5
  adminer:
    image: adminer:latest
