version: '3'
services:
  nginx:
    image: ninjacn/opendeploy_nginx:latest
  web:
    image: ninjacn/opendeploy:latest
    command: 'gunicorn opendeploy.wsgi:application --bind 0.0.0.0:8000'
    env_file: 
      - .env.prod
  worker:
    image: ninjacn/opendeploy:latest
    command: 'celery -A opendeploy worker --concurrency=5 -l info'
    env_file: 
      - .env.prod
  beat:
    image: ninjacn/opendeploy:latest
    env_file: 
      - .env.prod
  db:
    environment:
      MYSQL_DATABASE: opendeploy
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Wh4LsrGxpg59XUuH
      MYSQL_PASSWORD: Wh4LsrGxpg59XUuH
  rabbit:
      image: rabbitmq:latest
  redis:
      image: redis:5
  adminer:
    image: adminer:latest
