site_name: Opendeploy
repo_url: https://github.com/ninjacn/opendeploy
site_author: 姚鹏鸣<x@ninjacn.com>
copyright: null
theme: readthedocs
nav:
  - 概述: index.md
  - 安装及升级: 安装.md
  - 常规操作: 常规操作.md
  - Webhook: webhook.md
  - 钩子: hook.md
  - 消息通知: 消息通知.md
  - 常见问题: faq.md
