site_name: Opendeploy Docs
theme: readthedocs
repo_url: https://github.com/ninjacn/opendeploy
site_author: 姚鹏鸣<x@ninjacn.com>
copyright: null
google_analytics: ['UA-36723568-3', 'mkdocs.org']
lang: ['en']
