# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20181106_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='1', max_length=2),
        ),
    ]
