# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20181113_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostgroup',
            name='status',
            field=models.CharField(choices=[('1', '启用'), ('0', '禁用')], default='1', max_length=2),
        ),
    ]
