# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_hostgroup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='InstanceId',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='InstanceId'),
        ),
        migrations.AddField(
            model_name='host',
            name='provider',
            field=models.CharField(choices=[('OWN_IDC', '自有IDC'), ('aliyun', '阿里云'), ('qcloud', '腾讯云')], default='OWN_IDC', max_length=16, verbose_name='服务商'),
        ),
    ]
