# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20181217_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='InstanceId',
        ),
        migrations.AddField(
            model_name='host',
            name='instance_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='InstanceId'),
        ),
        migrations.AlterField(
            model_name='host',
            name='provider',
            field=models.CharField(choices=[('own_idc', '自有IDC'), ('aliyun', '阿里云'), ('qcloud', '腾讯云')], default='own_idc', max_length=16, verbose_name='服务商'),
        ),
    ]
