# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userdetail',
            table='accounts_user_detail',
        ),
    ]
