# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181227_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='type',
            field=models.CharField(choices=[('ldap', 'LDAP账号'), ('local', '本地账号')], default='local', max_length=10),
        ),
    ]
