# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('ldap', 'LDAP账号'), ('local', '本地账号')], default='local', max_length=10)),
                ('dingding', models.CharField(default='', max_length=64, null=True, verbose_name='dingding')),
                ('ldap_dn', models.CharField(default='', max_length=1024, null=True, verbose_name='ldap_dn')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'verbose_name': '用户附加表',
                'verbose_name_plural': '用户附加表',
                'db_table': 'accounts_user_detail',
            },
        ),
    ]
