# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 15:53
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from django.utils import timezone


def load_accounts(apps, schema_editor):
    try:
        raw_password = 'opendeploy'
        user = User()
        user.username = 'admin'
        user.first_name = 'admin'
        user.is_active = 1
        user.is_staff = 1
        user.is_superuser = 1
        user.last_login = timezone.now()
        user.set_password(raw_password)
        user.save()
    except:
        pass

def delete_accounts(apps, schema_editor):
    pass
    # User = apps.get_model("accounts", "User")
    # User.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_accounts, delete_accounts),
    ]
