# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 07:46
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User
from django.utils import timezone

def load_accounts(apps, schema_editor):
    try:
        raw_password = ''
        user = User()
        user.username = 'git_robot'
        user.first_name = 'Git机器人'
        user.is_active = 1
        user.is_staff = 0
        user.is_superuser = 0
        user.last_login = timezone.now()
        user.set_password(raw_password)
        user.save()
    except:
        pass

def delete_accounts(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190109_2134'),
    ]

    operations = [
        migrations.RunPython(load_accounts, delete_accounts),
    ]
