# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_register', models.BooleanField(default=True, verbose_name='开启用户注册')),
            ],
            options={
                'verbose_name': '设置 - 通用',
                'verbose_name_plural': '设置 - 通用',
                'db_table': 'setting_general',
            },
        ),
        migrations.CreateModel(
            name='SettingLdap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(default='', max_length=255, verbose_name='发送人')),
                ('port', models.CharField(default='389', max_length=255, verbose_name='发送人')),
                ('uid', models.CharField(default='uid', max_length=255, verbose_name='uid')),
                ('base', models.CharField(default='uid', max_length=255, verbose_name='base')),
                ('bind_dn', models.CharField(default='', max_length=255, verbose_name='bind_dn')),
                ('password', models.CharField(default='', max_length=255, verbose_name='密码')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
            ],
            options={
                'verbose_name': '设置 - LDAP',
                'verbose_name_plural': '设置 - LDAP',
                'db_table': 'setting_ldap',
            },
        ),
        migrations.CreateModel(
            name='SettingMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(default='', help_text='例: opendeploy@ninjacn.com或Opendeploy<opendeploy@ninjacn.com>', max_length=255, verbose_name='发送人')),
                ('host', models.CharField(default='', help_text='例: smtp.exmail.qq.com', max_length=255, verbose_name='SMTP主机')),
                ('port', models.CharField(default='25', help_text='25', max_length=255, verbose_name='端口')),
                ('username', models.CharField(default='', max_length=255, verbose_name='发送人账号')),
                ('password', models.CharField(blank=True, default='', max_length=255, verbose_name='发送人密码')),
                ('use_tls', models.BooleanField(default=False, verbose_name='TLS')),
            ],
            options={
                'verbose_name': '设置 - 邮箱',
                'verbose_name_plural': '设置 - 邮箱',
                'db_table': 'setting_mail',
            },
        ),
        migrations.CreateModel(
            name='SettingPublicCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliyun_access_key_id', models.CharField(default='', max_length=255, verbose_name='AccessKeyID')),
                ('aliyun_access_key_secret', models.CharField(default='', max_length=255, verbose_name='AccessKeySecret')),
                ('qcloud_secret_id', models.CharField(default='', max_length=255, verbose_name='SecretId')),
                ('qcloud_secret_key', models.CharField(default='', max_length=255, verbose_name='SecretKey')),
            ],
            options={
                'verbose_name': '设置 - 公有云',
                'verbose_name_plural': '设置 - 公有云',
                'db_table': 'setting_public_cloud',
            },
        ),
    ]
