# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingpubliccloud',
            name='aliyun_access_key_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='阿里云-AccessKeyID'),
        ),
        migrations.AlterField(
            model_name='settingpubliccloud',
            name='aliyun_access_key_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='阿里云-AccessKeySecret'),
        ),
        migrations.AlterField(
            model_name='settingpubliccloud',
            name='qcloud_secret_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='腾讯云-SecretId'),
        ),
        migrations.AlterField(
            model_name='settingpubliccloud',
            name='qcloud_secret_key',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='腾讯云-SecretKey'),
        ),
    ]
