# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-08 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinggeneral',
            name='site_url',
            field=models.URLField(default='', help_text='比如:http://opendeploy.ninjacn.com, 结尾不用带/', max_length=255, verbose_name='站点域名'),
        ),
    ]
