# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_settinggeneral_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinggeneral',
            name='enable_register',
            field=models.BooleanField(default=False, verbose_name='开启用户注册'),
        ),
    ]
