# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-24 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20181224_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinggeneral',
            name='site_url',
            field=models.URLField(default='', help_text='比如:http://opendeploy.ninjacn.com', max_length=255, verbose_name='站点域名'),
        ),
    ]
