# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20181224_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingldap',
            name='base',
        ),
        migrations.AlterField(
            model_name='settingldap',
            name='host',
            field=models.CharField(default='', max_length=255, verbose_name='主机地址'),
        ),
        migrations.AlterField(
            model_name='settingldap',
            name='port',
            field=models.CharField(default='389', max_length=255, verbose_name='端口'),
        ),
    ]
