# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_auto_20181227_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingldap',
            name='base',
            field=models.CharField(default='', max_length=255, verbose_name='base'),
        ),
    ]
