# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-27 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_settingldap_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingldap',
            name='base',
            field=models.CharField(default='', help_text='例: dc=ninjacn,dc=com', max_length=255, verbose_name='base'),
        ),
        migrations.AlterField(
            model_name='settingldap',
            name='bind_dn',
            field=models.CharField(default='', help_text='例: cn=admin,dc=ninjacn,dc=com', max_length=255, verbose_name='bind_dn'),
        ),
        migrations.AlterField(
            model_name='settingldap',
            name='host',
            field=models.CharField(default='', max_length=255, verbose_name='主机地址或域名'),
        ),
    ]
