# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20190108_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='version',
            field=models.CharField(default='', max_length=255, verbose_name='版本'),
        ),
    ]
