# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0008_project_enable_mail_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(default='', max_length=255, verbose_name='Celery Task id'),
        ),
    ]
