# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0009_task_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scope',
            field=models.IntegerField(choices=[(1, '按文件'), (0, '全量')], default=0, verbose_name='发布范围'),
        ),
    ]
